[package]
name = "infrastructure"
version = "0.1.0"
edition = "2026"

[dependencies]
soroban-sdk = "0.9.0"
security = { path = "../security" }
governance = { path = "../governance" }

[lib]
crate-type = ["cdylib"]
